version: '3'
services:
  react-app:
    image: react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - deploy.env
  strapi-app:
    tty: true
    image: strapi-app
    build:
      context: ./quill-engine-strapi
    ports:
      - "1337:1337"