name: CI/CD Pipeline PWA

on:
  push:
    branches:
      - master

jobs:
  build-and-push-to-dockerhub-pwa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./quill-engine-pwa
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}

  build-and-push-to-dockerhub-strapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./quill-engine-strapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:${{ github.sha }}

  deploy-to-digital-ocean:
    runs-on: ubuntu-latest

    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6 # replace this with current version from https://github.com/digitalocean/app_action/releases
        with:
          app_name: quill-engine-pwa
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
                    {
                      "name": "luoencz-react-app",
                       "image":{
                        "registry_type": "DOCKER_HUB",
                        "repository": "luoencz/react-app",
                        "tag": "${{ github.sha }}"
                      },
                    },
                    {
                      "name": "sample-add",
                      "image":{
                        "registry_type": "DOCKER_HUB",
                        registry: luoencz,
                        "repository": "luoencz/strapi-app",
                        "tag": "${{ github.sha }}"
                    },
                  ]'