name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Git config
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "<>"

      - name: Install Dependencies
        run: npm install --force

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build docker image of react-app
        run: docker build -t react-app:${{ github.sha }} .

      - name: Build docker image of strapi-app
        run: docker build -t strapi-app:${{ github.sha }} ./quill-engine-strapi

      - name: Tag docker image of react-app
        run: docker tag react-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}

      - name: Tag docker image of strapi-app
        run: docker tag strapi-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:${{ github.sha }}

      - name: Push docker image of react-app
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}

      - name: Push docker image of strapi-app
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:${{ github.sha }}

      - name: SSH and get strapi-app running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop strapi-app || true
            docker rm strapi-app || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:latest
            docker run -d --name strapi-app -p 1337:1337 ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:latest

      - name: SSH and get react-app running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop react-app || true
            docker rm react-app || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
            docker run -d --name react-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
