name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Git config
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "<>"

      - name: Install Dependencies
        run: npm install --force

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: Build docker image of react-app
        run: docker build -t react-app:${{ github.sha }} .

      - name: Build docker image of strapi-app
        run: docker build -t strapi-app:${{ github.sha }} ./quill-engine-strapi

      - name: Tag docker image of react-app
        run: docker tag react-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}

      - name: Tag docker image of strapi-app
        run: docker tag strapi-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:${{ github.sha }}

      - name: Push docker image of react-app
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}

      - name: Push docker image of strapi-app
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app:${{ github.sha }}

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: quill-engine-pwa
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
              {
                "name": "react-app",
                 "image": {
                  "registry_type": "DOCKER_HUB",
                  "repository": "luoencz/strapi-app",
                  "tag": "${{ github.sha }}"
                }
              },
              {
                "name": "strapi-app",
                "image":{
                  "registry_type": "DOCKER_HUB",
                  "repository": "luoencz/strapi-app",
                  "tag": "${{ github.sha }}"
                }
              }
            ]'
